import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/Container/Container";
import { kumbh } from "./_lib/fonts";
// import ContextComponent from "@/components/ContextComponent/ContextComponent";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${ kumbh.className } antialiased`}
      >
        <Header />
        <Container>
          {children}
        </Container>
      </body>
    </html>
  );
}
